"""Methods to extract a GPAD 2.0 from merged GAFs."""
from ontobio.ecomap import EcoMap
from ontobio.io.gafparser import GafParser
from pathlib import Path
from src.utils.decorators import timer
import datetime
import pystow


@timer
def configure_parser() -> GafParser:
    """
    Configures and returns a GafParser object.

    :return: A configured GafParser object.
    :rtype: GafParser
    """
    p = GafParser()
    p.config.ecomap = EcoMap()
    p.config.remove_double_prefixes = True
    return p

@timer
def get_gpad() -> Path:
    """
    Parses the GAF file and processes the annotations.

    :return: None.
    """
    merged_gaf_filepath = pystow.join(
        key="MGI",
        name="mgi-merged-ortho.gaf",
        ensure_exists=True,
    )
    gpad_rows = []
    p = configure_parser()
    with open(merged_gaf_filepath, "r") as file:
        for line in file:
            annotations = p.parse_line(line)
            if annotations:
                for assoc in annotations.associations:
                    if isinstance(assoc, dict):
                        continue  # skip the header
                    gpad_row = assoc.to_gpad_2_0_tsv()
                    gpad_rows.append(gpad_row)

    merged_gpad_filepath = pystow.join(
        key="MGI",
        name="mgi-merged-gpad.gaf",
        ensure_exists=True,
    )

    # here's the final write to the final file
    with open(merged_gpad_filepath, "w") as file:
        file.write("!gpad-version: 2.0\n")
        file.write("!Generated by: GO_Central preprocess pipeline: merged gaf gpad dump\n")
        file.write("!Date Generated: " + str(datetime.date.today()) + "\n")
        for row in gpad_rows:
            file.write("\t".join(map(str, row)) + "\n")

    return merged_gpad_filepath
